[secrets]
openai_api_key = "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"


gemini_api_key = "AIzaSyB1nm0dZ32kLeBGulTXY43ZXdNFi-bH_xo"